# Generated by Django 3.0.4 on 2020-04-01 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0002_auto_20200331_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('almacen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacenes.Almacen')),
                ('gasto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gastos.Tipo_Gasto')),
            ],
        ),
    ]
